#deployment do postgre

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
        app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "eudes123"
          - name: POSTGRES_USER
            value: "eudes"
          - name: POSTGRES_DB
            value: "kubeeudes"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeeudes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeeudes
  template:
    metadata:
      labels:
        app: kubeeudes
    spec:
      containers:
      - name: kubeeudes
        image: eudespaz/kubnews:v1
        env:
        - name: DB_DATABASE
          value: "kubeeudes"           
        - name: DB_USERNAME
          value: "eudes"
        - name: DB_PASSWORD
          value: "eudes123"
        - name: DB_HOST         
          value: "postgre"
---

apiVersion: v1
kind: Service
metadata:
  name: kube-eudes
spec:
  selector:
    app: kubeeudes
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000        
  type: NodePort

               
